spring.application.name=Spendy

#Info gral de la base de datos 
spring.datasource.url=jdbc:h2:mem:neoapp_bd
spring.datasource.username=sa
spring.datasource.password=
#Reactivación h2 1-muestra la consola de h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#Activacion jpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true